{
    "name": "Ranch Market - Stock Opname DC V.1",
    "version": "9.0.1.0.0",
    "category": "Warehouse",
    "author": "Mu_Ha_Ram",
    "website": "http://www.jakc-labs.com",
    "depends": [
        "stock",
    ],
    "data": [
        "security/stock_security.xml",
        "security/ir.model.access.csv",
        "wizard/import_inventory_view.xml",
        "views/stock_view.xml",
        "views/product_view.xml",
        "wizard/import_product_view.xml",
        "wizard/import_gondola_view.xml",
        "wizard/report_product_transaction_per_gondola_view.xml",
        "wizard/report_article_transaction_view.xml",
        "wizard/wizard_clear_data_view.xml",
        "wizard/export_all_data_view.xml",
        "reports/ranch_project_report.xml",
        "reports/report_product_transaction_per_gondola.xml",
        "reports/report_article_transaction.xml",
        "views/templates.xml",
    ],
    "installable": True,
    "application": True,
}
